# Cloudflare Pages 配置文件

name = "ai-image-tools"
compatibility_date = "2024-01-01"

# Pages 配置
pages_build_output_dir = "."

# 环境变量（本地开发用）
[vars]
ENVIRONMENT = "production"

# 生产环境
[[env.production]]
name = "ai-image-tools"

# 注意：敏感信息（API密钥）应该在 Cloudflare Dashboard 中配置
# 不要在此文件中写入真实的API密钥

